/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package INTF;

import SYS.ovcconn;
import com.sun.org.apache.xalan.internal.xsltc.compiler.util.ErrorMsg;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;

/**
 *
 * @author KaviRox
 */
public class Addmovie extends javax.swing.JFrame {

    /**
     * Creates new form Addmovie
     */
    public Addmovie() {
        initComponents();
        jButton2.setEnabled(false);
        autogen();
         setLocationRelativeTo(null);
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/IMG/om.GIF")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        blueray = new javax.swing.JRadioButton();
        dvd = new javax.swing.JRadioButton();
        hd = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        title = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        director = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        genere = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        studio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        made = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        mainactor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        cast = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        story = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        copy = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        running = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        country = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        dd = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 0, 51));

        jLabel1.setFont(new java.awt.Font("Zurich Ex BT", 1, 24)); // NOI18N
        jLabel1.setText("Add Movie");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(321, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(346, 346, 346))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Movie Title");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 20));

        blueray.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(blueray);
        blueray.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        blueray.setForeground(new java.awt.Color(0, 51, 204));
        blueray.setText("1080p(Blue-Ray)");
        blueray.setFocusPainted(false);
        blueray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bluerayActionPerformed(evt);
            }
        });
        jPanel1.add(blueray, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 150, -1));

        dvd.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(dvd);
        dvd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dvd.setForeground(new java.awt.Color(204, 0, 0));
        dvd.setText("DVD");
        dvd.setFocusPainted(false);
        dvd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dvdActionPerformed(evt);
            }
        });
        jPanel1.add(dvd, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        hd.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(hd);
        hd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hd.setForeground(new java.awt.Color(0, 51, 204));
        hd.setText("720P(Blue-Ray)");
        hd.setFocusPainted(false);
        hd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hdActionPerformed(evt);
            }
        });
        jPanel1.add(hd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Quality ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 20));
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 150, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Movie Poster"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, 140, 210));

        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 430, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Director");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 20));
        jPanel1.add(director, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 150, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Genere");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 20));
        jPanel1.add(genere, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 150, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Studio");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Relese Date");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, 20));

        studio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studioActionPerformed(evt);
            }
        });
        jPanel1.add(studio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 150, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Copies");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, -1, 20));
        jPanel1.add(made, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 150, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Cast");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Movie ID");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, -1, -1));

        ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ID.setForeground(new java.awt.Color(0, 0, 204));
        ID.setText("00000");
        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Main Actor");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, 20));
        jPanel1.add(mainactor, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 150, -1));

        cast.setColumns(20);
        cast.setRows(5);
        jScrollPane1.setViewportView(cast);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 190, 120));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Story Line");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, -1, 20));

        story.setColumns(20);
        story.setRows(5);
        jScrollPane2.setViewportView(story);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 190, 120));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Year Of Made");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, 20));

        copy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyActionPerformed(evt);
            }
        });
        jPanel1.add(copy, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 60, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Running Time");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, 20));
        jPanel1.add(running, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 150, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Country");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, 20));
        jPanel1.add(country, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 150, -1));

        jButton2.setText("Add Movie");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 513, 100, 30));

        jDateChooser1.setDateFormatString("yyy-MM-dd");
        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 150, -1));

        dd.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(dd);
        dd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dd.setForeground(new java.awt.Color(155, 26, 217));
        dd.setText("3D(Blue-Ray)");
        dd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddActionPerformed(evt);
            }
        });
        jPanel1.add(dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));

        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setText("Designed & Developed by © K.V.R Creatives");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 540, 220, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int a1;

    public void autogen() {

        try {

            Statement s = ovcconn.DB().createStatement();
            ResultSet rs = s.executeQuery("SELECT MAX(movie_id) FROM movie_lib");

            while (rs.next()) {

                int a = rs.getInt("MAX(movie_id)");
                a1 = a + 1;
                String id = "" + a1;
                ID.setText(id);

            }

        } catch (Exception e) {
        }

    }
    private void bluerayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bluerayActionPerformed

        if (blueray.isSelected()) {

            jButton2.setEnabled(true);

        }
    }//GEN-LAST:event_bluerayActionPerformed

    private void hdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hdActionPerformed

        if (hd.isSelected()) {

            jButton2.setEnabled(true);

        }
    }//GEN-LAST:event_hdActionPerformed

    double price;
    String qu;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (dvd.isSelected()) {

            price = 100.00;
            qu = "DVD";
        } else if (hd.isSelected()) {

            price = 250.00;
            qu = "720P(Blue-Ray)";
        } else if (blueray.isSelected()) {

            price = 350.00;
            qu = "1080p(Blue-Ray)";
            
        }else if(dd.isSelected()){
        
            price = 500.00;
            qu = "3D(Blue-Ray)";
        
        } else {
            
            JOptionPane.showMessageDialog(this, "Please Select Quality");

        }
        
          if(copy.getText() == null){
          
              JOptionPane.showMessageDialog(this, "Please Enter Cpoies Quantity.....");
              
          }else{  
        try {
            Statement s = ovcconn.DB().createStatement();
            s.executeUpdate("INSERT INTO movie_lib(movie_id,quality,name,genere,director,studio,relese_date,made_year,running_time,country,main_actor,cast,story_line,copies,poster,price) VALUES('"+a1+"','" + qu + "','" + title.getText() + "','" + genere.getText() + "','"+director.getText()+"','"+studio.getText()+"','"+date+"','"+made.getText()+"','"+running.getText()+"','"+country.getText()+"','"+mainactor.getText()+"','"+cast.getText()+"','"+story.getText()+"','"+copy.getText()+"','"+newpath+"','"+price+"')");
            s.executeUpdate("INSERT INTO movie_stock(movie_id,copies) VALUES('"+a1+"','"+copy.getText()+"')");
           
            copy.setText(null);
            title.setText(null);
            genere.setText(null);
            director.setText(null);
            cast.setText(null);
            mainactor.setText(null);
            country.setText(null);
            studio.setText(null);
            running.setText(null);
            made.setText(null);
            story.setText(null);
            image.setIcon(null);
            jDateChooser1.setDate(null);
            JOptionPane.showMessageDialog(this, "Movie Addes Successfully..!");
            
            
            autogen();
            
            

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, JOptionPane.ERROR_MESSAGE);
            
        }
          }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void copyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_copyActionPerformed

    private void studioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studioActionPerformed

    String date;
    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange

        date = ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText();

    }//GEN-LAST:event_jDateChooser1PropertyChange

    private void dvdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dvdActionPerformed

        if (dvd.isSelected()) {

            jButton2.setEnabled(true);

        }
    }//GEN-LAST:event_dvdActionPerformed

    String newpath;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try {
            JFileChooser jf = new JFileChooser();
            
            jf.showOpenDialog(this);
            
            File f = jf.getSelectedFile();
            String path = f.getAbsolutePath();
            newpath = path.replace("\\", "/");
            
            File ff = new File(newpath);
            Image img = ImageIO.read(ff);
            img = img.getScaledInstance(image.getWidth(), image.getHeight(), Image.SCALE_SMOOTH);
            image.setIcon(new ImageIcon(img));
            
            
            
            
            
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddActionPerformed
        
        if (dd.isSelected()) {

            jButton2.setEnabled(true);

        }
    }//GEN-LAST:event_ddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {

            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

        } catch (Exception e) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addmovie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID;
    private javax.swing.JRadioButton blueray;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea cast;
    private javax.swing.JTextField copy;
    private javax.swing.JTextField country;
    private javax.swing.JRadioButton dd;
    private javax.swing.JTextField director;
    private javax.swing.JRadioButton dvd;
    private javax.swing.JTextField genere;
    private javax.swing.JRadioButton hd;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField made;
    private javax.swing.JTextField mainactor;
    private javax.swing.JTextField running;
    private javax.swing.JTextArea story;
    private javax.swing.JTextField studio;
    private javax.swing.JTextField title;
    // End of variables declaration//GEN-END:variables
}
