/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package INTF;

import static INTF.Home.loginnamw;
import static INTF.Home.loginnamw1;
import SYS.ovcconn;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author KaviRox
 */
public class Bill extends javax.swing.JFrame {

    /**
     * Creates new form Bill
     */
    public Bill() {
        initComponents();
        jPanel3.setVisible(false);
        setLocationRelativeTo(null);
        showDate();
        user();
        jPanel4.setVisible(false);
        jLabel1.setVisible(false);
        setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/IMG/om.GIF")));

    }

    public void showDate() {
        Date d = new Date();
        SimpleDateFormat sd = new SimpleDateFormat("dd-MM-yyyy");
        String dt = sd.format(d);
        date.setText(dt);
        showid();
    }

    String user;

    public void user() {

        Home h = new Home();
        user = h.loginnamw1.getText();

    }

    public void showid() {

        try {

            Statement s = ovcconn.DB().createStatement();
            ResultSet rs = s.executeQuery("SELECT MAX(bill_id) FROM billing");

            while (rs.next()) {

                int i = rs.getInt("MAX(bill_id)");
                ii = i + 1;
                String ai = "" + ii;
                bid.setText(ai);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    int ii;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        bid = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        balance = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textFieldCM1 = new DW.TextFieldCM();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 0, 51));

        jLabel2.setFont(new java.awt.Font("Zurich Ex BT", 1, 24)); // NOI18N
        jLabel2.setText("Billing");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(jLabel2)
                .addContainerGap(409, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Customer Name :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 240, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("Bill ID");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, -1, -1));

        date.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 120, 20));

        bid.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        bid.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(bid, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 120, 20));

        jRadioButton1.setText("Registered User");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item No", "Movie ID", "Movie Name", "Quality", "Quantity", "Unit Price", "Sub Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 740, 190));

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 50, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Quantity");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("Grand Total");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, -1, -1));

        balance.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel1.add(balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 540, 100, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setText("Payment");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 460, 100, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setText("Movie Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel8.setText("Date");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, -1, -1));

        textFieldCM1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFieldCM1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldCM1KeyTyped(evt);
            }
        });
        jPanel1.add(textFieldCM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 140, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 140, 60));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 544, 10, 10));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, 100, -1));

        jButton1.setText("Delete Items");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed

        if (jRadioButton1.isSelected()) {

            new Client_Veri().setVisible(true);
            DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
            dt.setRowCount(0);

        } else {

            jPanel3.setVisible(false);

        }

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void textFieldCM1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldCM1KeyReleased

        Search();
    }//GEN-LAST:event_textFieldCM1KeyReleased

    int i;
    String il;
    String ite;
    double dis;
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        try {
            
            String qi = (String) jComboBox1.getSelectedItem();
            
            if(qi.equals("0")){
            
            
            }
            double q = Double.parseDouble(qi);
            DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();

            double sub = q * d;
            
            String sub2 = ""+sub;

            Vector v = new Vector();

            v.add(il);
            v.add(idm);
            v.add(ss);
            v.add(qu);
            v.add(qi);
            v.add(pr+".00");
            v.add(sub2+"0");
            dt.addRow(v);

            jPanel4.setVisible(false);
            jComboBox1.setSelectedIndex(0);
            textFieldCM1.setText(null);

            double d = 0;
            for (int i = 0; i < dt.getRowCount(); i++) {
                double dd = Double.parseDouble(dt.getValueAt(i, 6).toString());
                d += dd;
                jLabel14.setText(d + "0");

            }

        } catch (Exception e) {
            
        }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void textFieldCM1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldCM1KeyTyped

        Search();
    }//GEN-LAST:event_textFieldCM1KeyTyped

    String idm;
    String qu;
    String pri;
    double d;
    String ss;
    String pr;
    int qty;
    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked


        i = i + 1;
        il = i+"";
        
        
        try {
            ss = (String) jList1.getSelectedValue();
            textFieldCM1.setText(ss);
            Statement s = ovcconn.DB().createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM movie_lib WHERE name = '" + ss + "'");

            while (rs.next()) {

                idm = rs.getString(1);
                qu = rs.getString(2);
                pr = rs.getString(16);
                qty = rs.getInt(14);
                
                jComboBox1.removeAllItems();
                jComboBox1.addItem(0);
                
                for (int j = 1; j <= qty; j++) {
                    
                    jComboBox1.addItem(j+"");
                    
                }

                if (jLabel1.getText().equals("OK")) {

                    double de = Double.parseDouble(pr);

                    double se = de - (de * 5) / 100;

                    pri = "" + se;
                    
                    

                } else {

                    pri = rs.getString(16);

                }

                d = Double.parseDouble(pri);
                
                
            }
            
            jPanel4.setVisible(false);
            JOptionPane.showMessageDialog(this, "Please Select the Quantity..");

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jList1MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked

        jPanel4.setVisible(false);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped


    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed

        char c1 = evt.getKeyChar();

        int i = jTextField1.getText().length();

        if (!(c1 >= '0' && c1 <= '9')) {

            evt.consume();
            Toolkit.getDefaultToolkit().beep();

        }

        try {

            if (evt.getKeyCode() == 10) {

                double gr = Double.parseDouble(jLabel14.getText());
                double py = Double.parseDouble(jTextField1.getText());

                if (gr > py) {

                    JOptionPane.showMessageDialog(this, "Insufficent Payment.......");
                    jTextField1.setText(null);

                } else {

                    double ba = py - gr;
                    balance.setText("" + ba);

                    Statement s = ovcconn.DB().createStatement();
                    s.executeUpdate("INSERT INTO billing(bill_id,amount,date) VALUES('" + bid.getText() + "','" + jLabel14.getText() + "','" + date.getText() + "')");

                    DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                    int rwc = dtm.getRowCount();

                    for (int rw = 0; rw < rwc; rw++) {

                        String bd = bid.getText();
                        String mid = dtm.getValueAt(rw, 1).toString();
                        String qu = dtm.getValueAt(rw, 4).toString();
                        String prie = dtm.getValueAt(rw, 5).toString();
                        String to = dtm.getValueAt(rw, 6).toString();

                        s.executeUpdate("INSERT INTO bill_registry(bill_id,movie_id,quantity,price,totla) VALUES('" + bd + "','" + mid + "','" + qu + "','" + prie + "','" + to + "')");

                        String up = null;
                        ResultSet rs = s.executeQuery("SELECT * from movie_lib WHERE movie_id = '" + bid.getText() + "'");
                        while (rs.next()) {

                            int c = Integer.parseInt(rs.getString(14));
                            int qi = Integer.parseInt(qu);
                            int cc = c - qi;
                            up = "" + cc;
                            System.out.println(up);

                        }

                        s.executeUpdate("UPDATE movie_lib SET copies = '" + up + "' WHERE movie_id = '" + bid.getText() + "'");
                        s.executeUpdate("UPDATE movie_stock SET copies = '" + up + "' WHERE movie_id = '" + bid.getText() + "'");

                    }

                    String da = date.getText();
                    String bill = bid.getText();
                    String tot = jLabel14.getText();
                    String pay = py+"0";
                    String balance2 = ba+"0";

                    String path = "E:\\My Documents\\SE Projects\\OVC_Reports\\OVC.JRXML";
                    JRTableModelDataSource data = new JRTableModelDataSource(jTable1.getModel());
                    Map<String, Object> params = new HashMap();
                    params.put("para1", da);
                    params.put("para2", user);
                    params.put("para3", bill);
                    params.put("para4", tot);
                    params.put("para5", pay);
                    params.put("para6", balance2);
                    JasperReport jr = JasperCompileManager.compileReport(path);
                    JasperPrint p = JasperFillManager.fillReport(jr, params,data);
                    JasperViewer.viewReport(p, false);
                    

                    showid();
                    jLabel14.setText(null);
                    jTextField1.setText(null);
                    balance.setText(null);
                    dtm.setRowCount(0);
                    JOptionPane.showMessageDialog(this, "Bill Paid..\nBalance : " + ba + "0");
                    

                   

                }

            }
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        int sr = jTable1.getSelectedRow();

        dtm.removeRow(sr);

        double d = 0;
        for (int i = 0; i < dtm.getRowCount(); i++) {
            double dd = Double.parseDouble(dtm.getValueAt(i, 6).toString());
            d += dd;
            jLabel14.setText(d + "");

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
    
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    public void Search() {

        jPanel4.setVisible(true);
        try {

            Statement s = ovcconn.DB().createStatement();
            String ad = "name";
            ResultSet rs = ovcconn.DB().createStatement().executeQuery("SELECT * FROM `movie_lib` WHERE " + ad + " LIKE '" + textFieldCM1.getText() + "%'");
            Vector v = new Vector();
            while (rs.next()) {

                v.add(rs.getString(3));

            }
            jList1.setListData(v);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel balance;
    private javax.swing.JLabel bid;
    private javax.swing.JLabel date;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private DW.TextFieldCM textFieldCM1;
    // End of variables declaration//GEN-END:variables
}
