package INTF;

import SYS.ovcconn;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ahamed azhar
 */
public class Createuser extends javax.swing.JFrame {

    /**
     * Creates new form creatuser
     */
    public Createuser() {
        initComponents();
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        setLocationRelativeTo(null);
        jPanel2.setVisible(false);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/IMG/om.GIF")));

        //setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/midas logo new.JPG")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txfna = new javax.swing.JTextField();
        txuserna = new javax.swing.JTextField();
        txemail = new javax.swing.JTextField();
        txln = new javax.swing.JTextField();
        txmn = new javax.swing.JTextField();
        txps = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        textFieldCM1 = new DW.TextFieldCM();
        comprivilage = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Zurich Ex BT", 0, 14)); // NOI18N
        jLabel2.setText("Creat New User Account");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 27, -1, -1));

        jLabel3.setText("UserName");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 187, -1, -1));

        jLabel4.setText("First Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 129, -1, -1));

        jLabel5.setText("Last Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 129, -1, -1));

        jLabel7.setText("Privilege Type");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 240, -1, 20));

        jLabel8.setText("Mobile No");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        jLabel9.setText("Email ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 297, -1, -1));

        jLabel10.setText("Password");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 187, -1, -1));

        txfna.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfnaKeyTyped(evt);
            }
        });
        jPanel1.add(txfna, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 126, 174, -1));
        jPanel1.add(txuserna, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 184, 174, -1));
        jPanel1.add(txemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 294, 174, -1));
        jPanel1.add(txln, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 126, 167, -1));

        txmn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txmnKeyTyped(evt);
            }
        });
        jPanel1.add(txmn, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 237, 167, -1));

        txps.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txpsMouseClicked(evt);
            }
        });
        txps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txpsActionPerformed(evt);
            }
        });
        txps.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txpsKeyTyped(evt);
            }
        });
        jPanel1.add(txps, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 184, 167, -1));

        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 293, -1, -1));

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 293, -1, -1));

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 293, 77, -1));

        jRadioButton1.setText("Edit User");
        jRadioButton1.setContentAreaFilled(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 66, -1, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        textFieldCM1.setHint("Enter User Name");
        textFieldCM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCM1ActionPerformed(evt);
            }
        });
        textFieldCM1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldCM1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textFieldCM1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textFieldCM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 66, 170, -1));

        comprivilage.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Standard User", "Admin" }));
        comprivilage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comprivilageMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                comprivilageMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                comprivilageMouseReleased(evt);
            }
        });
        comprivilage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprivilageActionPerformed(evt);
            }
        });
        jPanel1.add(comprivilage, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed

        if (jRadioButton1.isSelected()) {

            jButton3.setEnabled(true);
            jButton4.setEnabled(true);
            jPanel2.setVisible(true);

            txfna.setText(null);
            txemail.setText(null);
            txln.setText(null);
            txuserna.setText(null);
            txps.setText(null);
            txmn.setText(null);
            textFieldCM1.setText(null);
            
        } else {
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jPanel2.setVisible(false);

            txfna.setText(null);
            txemail.setText(null);
            txln.setText(null);
            txuserna.setText(null);
            txps.setText(null);
            txmn.setText(null);
            textFieldCM1.setText(null);
            comprivilage.setSelectedIndex(0);
            

        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void txfnaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfnaKeyTyped

    }//GEN-LAST:event_txfnaKeyTyped

    private void textFieldCM1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldCM1KeyTyped

        try {
            Statement s = ovcconn.DB().createStatement();
            String ps = new String(txps.getPassword());

            ResultSet rs = s.executeQuery("Select * from user WHERE username='" + textFieldCM1.getText() + "' ");

            //JOptionPane.showMessageDialog(this, "Unkown Username");
            while (rs.next()) {

                if (jRadioButton1.isSelected()) {

                    txfna.setText(rs.getString(3));
                    txln.setText(rs.getString(4));
                    txuserna.setText(rs.getString(1));
                    txps.setText(rs.getString(2));
                    txemail.setText(rs.getString(7));
                    String p = rs.getString(5);

                    if (p.equals("Admin")) {

                        comprivilage.setSelectedItem("Admin");
                       
                        jButton1.setEnabled(false);
                        jButton4.setEnabled(false);
                        jButton3.setEnabled(false);
                    } 
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_textFieldCM1KeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        try {

            Statement s = ovcconn.DB().createStatement();
            String p = new String(txps.getPassword());
            String privilage;
            if (comprivilage.getSelectedIndex() == 1) {
                privilage = "Admin";
            } else {
                privilage = "Standard";
            }

            s.executeUpdate("UPDATE user SET Username = '" + txuserna.getText() + "',password = '" + p + "',first_name = '" + txfna.getText() + "',last_name = '" + txln.getText() + "',mobile = '" + txmn.getText() + "',email = '" + txemail.getText() + "',Privilege_Type = '" + privilage + "' WHERE username = '" + textFieldCM1.getText() + "'");

            txfna.setText(null);
            txemail.setText(null);
            txln.setText(null);
            txuserna.setText(null);
            txps.setText(null);
            txmn.setText(null);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {

            Statement s = ovcconn.DB().createStatement();
            String p = new String(txps.getPassword());

            String privilage;
            String stat;
            if (comprivilage.getSelectedIndex() == 1) {
                privilage = "Admin";
                stat = "null";
            } else {
                privilage = "Standard";
                stat = "null";
            }

            s.executeUpdate("INSERT INTO user VALUES('" + txuserna.getText() + "','" + p + "','" + txfna.getText() + "','" + txln.getText() + "','" + privilage + "','" + txmn.getText() + "','" + txemail.getText() + "')");

            txfna.setText(null);
            txemail.setText(null);
            txln.setText(null);
            txuserna.setText(null);
            txps.setText(null);
            txmn.setText(null);
            JOptionPane.showMessageDialog(this, "User Created Successfully");

        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void txpsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txpsMouseClicked

//        if(jRadioButton1.isSelected()){
//        
//            new Passwordvertify().setVisible(true);
//         jButton1.setVisible(false);
//           jButton3.setVisible(false);
//          jButton4.setVisible(false);
//            
//        }

    }//GEN-LAST:event_txpsMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        int i = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this User from Midas Application?", "Delete", JOptionPane.YES_NO_OPTION);
        if (i == JOptionPane.YES_OPTION) {
            try {

                Statement s = ovcconn.DB().createStatement();
                s.executeUpdate("DELETE FROM user WHERE username = '" + textFieldCM1.getText() + "'");
                JOptionPane.showMessageDialog(this, "User Deleted");

                txfna.setText(null);
                txemail.setText(null);
                txln.setText(null);
                txuserna.setText(null);
                txps.setText(null);
                txmn.setText(null);

                JOptionPane.showMessageDialog(this, "User Deleted");

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void textFieldCM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCM1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCM1ActionPerformed

    private void txpsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txpsKeyTyped

//            jButton1.setVisible(false);
//            jButton3.setVisible(false);
//            jButton4.setVisible(false);

    }//GEN-LAST:event_txpsKeyTyped

    private void txpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txpsActionPerformed

// if(jRadioButton1.isSelected()){
//        
//            new Passwordvertify().setVisible(true);
//            
//            
//            }
    }//GEN-LAST:event_txpsActionPerformed

    private void txmnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txmnKeyTyped

        char c1 = evt.getKeyChar();

        int i = txmn.getText().length();

        if (!(c1 >= '0' && c1 <= '9')) {

            evt.consume();
            Toolkit.getDefaultToolkit().beep();

        } else if (i == 10) {

            evt.consume();
            Toolkit.getDefaultToolkit().beep();

        }
    }//GEN-LAST:event_txmnKeyTyped

    private void comprivilageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprivilageActionPerformed

        //         if(comprivilage.getSelectedIndex()==1){
            //
            //             new Adminvertify().setVisible(true);
            //
            //
            //        }
    }//GEN-LAST:event_comprivilageActionPerformed

    private void comprivilageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comprivilageMousePressed

    }//GEN-LAST:event_comprivilageMousePressed

    private void comprivilageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comprivilageMouseClicked

    }//GEN-LAST:event_comprivilageMouseClicked

    private void comprivilageMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comprivilageMouseReleased

    }//GEN-LAST:event_comprivilageMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Createuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Createuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Createuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Createuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Createuser().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox comprivilage;
    public static javax.swing.JButton jButton1;
    protected static javax.swing.JButton jButton3;
    public static javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    public static DW.TextFieldCM textFieldCM1;
    private javax.swing.JTextField txemail;
    private javax.swing.JTextField txfna;
    private javax.swing.JTextField txln;
    private javax.swing.JTextField txmn;
    public static javax.swing.JPasswordField txps;
    private javax.swing.JTextField txuserna;
    // End of variables declaration//GEN-END:variables
}
