/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package INTF;

import SYS.ovcconn;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author KaviRox
 */
public class Supplier extends javax.swing.JFrame {

    /**
     * Creates new form Supplier
     */
    public Supplier() {
        initComponents();
        jPanel3.setVisible(false);
        autogen();
         setLocationRelativeTo(null);
          setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/IMG/om.GIF")));
    }

    int ii;

    public void autogen() {

        try {

            Statement s = ovcconn.DB().createStatement();
            ResultSet rs = s.executeQuery("SELECT MAX(supplier_id) FROM supplier_lib");

            while (rs.next()) {

                int i = rs.getInt("MAX(supplier_id)");
                ii = i + 1;
                String ai = "" + ii;
                id.setText(ai);

            }

        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        sid = new DW.TextFieldCM();
        id = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cover = new javax.swing.JRadioButton();
        movi = new javax.swing.JRadioButton();
        dvd = new javax.swing.JRadioButton();
        blue = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioButton1.setText("Search");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 50, 90, -1));

        jPanel2.setBackground(new java.awt.Color(255, 0, 51));

        jLabel2.setFont(new java.awt.Font("Zurich Ex BT", 1, 24)); // NOI18N
        jLabel2.setText("Add Supplier");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jLabel2)
                .addContainerGap(205, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sid.setToolTipText("Search");
        sid.setHint("Search");
        sid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sidKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sidKeyTyped(evt);
            }
        });
        jPanel3.add(sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 20, 120, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 140, 60));

        id.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        id.setText("00");
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 40, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("Supplier ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 170, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("Address");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 170, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("Mobile No");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        mobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mobileKeyTyped(evt);
            }
        });
        jPanel1.add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 170, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setText("Supplier Type");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));
        jPanel1.add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 170, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel8.setText("E-Mail");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        buttonGroup1.add(cover);
        cover.setText("Covers");
        cover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coverActionPerformed(evt);
            }
        });
        jPanel1.add(cover, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 110, -1));

        buttonGroup1.add(movi);
        movi.setText("Movie ");
        jPanel1.add(movi, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 110, -1));

        buttonGroup1.add(dvd);
        dvd.setText("DVD");
        dvd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dvdActionPerformed(evt);
            }
        });
        jPanel1.add(dvd, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 110, -1));

        buttonGroup1.add(blue);
        blue.setText("Blue-Ray");
        blue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueActionPerformed(evt);
            }
        });
        jPanel1.add(blue, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 110, -1));

        jButton1.setText("Add Supplier");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed

        if (jRadioButton1.isSelected()) {

            jPanel3.setVisible(true);
            jButton1.setText("Update");
            name.setText(null);
            address.setText(null);
            mobile.setText(null);
            mail.setText(null);
            buttonGroup1.clearSelection();

        } else {

            jPanel3.setVisible(false);
            jButton1.setText("Add Supplier");
            sid.setText(null);
            name.setText(null);
            address.setText(null);
            mobile.setText(null);
            mail.setText(null);
           buttonGroup1.clearSelection();

        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void coverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coverActionPerformed

    private void dvdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dvdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dvdActionPerformed

    private void blueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blueActionPerformed

    String type;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (jButton1.getText().equals("Add Supplier")) {

            save();

        } else if (jButton1.getText().equals("Update")) {

            update();
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void sidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sidKeyPressed

        if (evt.getKeyCode() == 10) {

            search();
        }
    }//GEN-LAST:event_sidKeyPressed

    private void sidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sidKeyTyped


    }//GEN-LAST:event_sidKeyTyped

    private void mobileKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobileKeyTyped
        
        char c1 = evt.getKeyChar();
         
        int i = mobile.getText().length();
       
         
         
      if(!(c1 >= '0' && c1 <= '9')){
      
          evt.consume();
          Toolkit.getDefaultToolkit().beep();
      
      }else if(i==10){
        
          evt.consume();
          Toolkit.getDefaultToolkit().beep();
            
        }
    }//GEN-LAST:event_mobileKeyTyped

    public void save() {

        if (movi.isSelected()) {

            type = "Movie";

        } else if (dvd.isSelected()) {

            type = "DVD";

        } else if (blue.isSelected()) {

            type = "Blue_Ray";

        } else if (cover.isSelected()) {

            type = "Covers";

        }

        try {

            Statement s = ovcconn.DB().createStatement();
            s.executeUpdate("INSERT INTO supplier_lib(supplier_id,name,address,mobile_no,e_mail,type) VALUES('" + id.getText() + "','" + name.getText() + "','" + address.getText() + "','" + mobile.getText() + "','" + mail.getText() + "','" + type + "')");

            JOptionPane.showMessageDialog(this, "Supplier Added Successfully...!");
            sid.setText(null);
            name.setText(null);
            address.setText(null);
            mobile.setText(null);
            mail.setText(null);
            buttonGroup1.clearSelection();
            
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void update() {

        try {

            Statement s = ovcconn.DB().createStatement();
            s.executeUpdate("UPDATE supplier_lib SET name = '" + name.getText() + "',address = '" + address.getText() + "',mobile_no = '" + mobile.getText() + "',e_mail = '" + mail.getText() + "',type = '" + type + "' WHERE supplier_id = '" + sid.getText() + "'");

            JOptionPane.showMessageDialog(this, "Supplier Updated Successfully..!");
            sid.setText(null);
            name.setText(null);
            address.setText(null);
            mobile.setText(null);
            mail.setText(null);
            buttonGroup1.clearSelection();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void search() {

        try {

            Statement s = ovcconn.DB().createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM supplier_lib WHERE supplier_id = '" + sid.getText() + "'");

            if (rs.next()) {

                name.setText(rs.getString(2));
                address.setText(rs.getString(3));
                mobile.setText(rs.getString(4));
                mail.setText(rs.getString(5));

                if (rs.getString(6).equals("Blue_Ray")) {

                    blue.setSelected(true);

                } else if (rs.getString(6).equals("DVD")) {

                    dvd.setSelected(true);

                } else if (rs.getString(6).equals("Covers")) {

                    cover.setSelected(true);

                } else if (rs.getString(6).equals("Movie")) {

                    movi.setSelected(true);
                    

                }

            } else {

                JOptionPane.showMessageDialog(this, "No Such a Supplier ID");

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JRadioButton blue;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cover;
    private javax.swing.JRadioButton dvd;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField mobile;
    private javax.swing.JRadioButton movi;
    private javax.swing.JTextField name;
    private DW.TextFieldCM sid;
    // End of variables declaration//GEN-END:variables
}
